apiVersion: v1
kind: Secret
metadata:
  name: airflow-secrets
  labels:
    app.kubernetes.io/part-of: airflow
  annotations:
    xccelerated.io/owner: mbrouns
data:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3c6YWlyZmxvd0BtZXRhZGF0YS1kYi9haXJmbG93 # postgresql+psycopg2://airflow:airflow@metadata-db/airflow
  AIRFLOW__WEBSERVER__SECRET_KEY: YWlyZmxvd19zZWNyZXQ= # airflow_secret
  AIRFLOW__CORE__FERNET_KEY: aV9mZDZERUlmRVdYVkd6QmgxYnY5SDNkcnV6cGFGZkVPQVRlMEVoR2hOYz0= # i_fd6DEIfEWXVGzBh1bv9H3druzpaFfEOATe0EhGhNc=
  AIRFLOW__CELERY__RESULT_BACKEND: ZGIrcG9zdGdyZXNxbDovL2FpcmZsb3c6YWlyZmxvd0BtZXRhZGF0YS1kYi9haXJmbG93 # db+postgresql://airflow:airflow@metadata-db/airflow
  AIRFLOW__CELERY__BROKER_URL: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA== # redis://redis-service:6379/0

