apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-cfg
  labels:
    app.kubernetes.io/part-of: airflow
  annotations:
    xccelerated.io/owner: mbrouns
data:
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
  # AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
  AIRFLOW__API__AUTH_BACKEND: 'airflow.api.auth.backend.basic_auth'
  AIRFLOW__CORE__EXECUTOR: CeleryExecutor


