apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: airflow-webserver
  ports:
  - name: web
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  labels:
    app.kubernetes.io/part-of: airflow
  annotations:
    xccelerated.io/owner: mbrouns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: apache/airflow:2.3.4 # 2.2.3, 2.3.4
          command:
            - airflow
            - webserver
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: airflow-cfg
            - secretRef:
                name: airflow-secrets
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: dags
        - name: dag-fetcher
          image: amazon/aws-cli:2.7.33
          command: ["sh","-c","while true; do aws s3 sync s3://xcc-example-dags /opt/airflow/dags --delete --no-sign-request; sleep 30; done"]
          volumeMounts:
            - mountPath: /opt/airflow/dags
              name: dags
      volumes:
        - name: dags
          emptyDir: {}

