apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  labels:
    app.kubernetes.io/part-of: airflow
data:
  POSTGRESQL_PASSWORD: YWlyZmxvdw==  # airflow
  POSTGRESQL_REPLICATION_PASSWORD: YWlyZmxvd19yZXBs  # airflow_repl
