apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-cfg
  labels:
    app.kubernetes.io/part-of: airflow
data:
  POSTGRESQL_USERNAME: airflow
  POSTGRESQL_DATABASE: airflow
  POSTGRESQL_MASTER_HOST: metadata-db
  POSTGRESQL_MASTER_PORT_NUMBER: '5432'
  POSTGRESQL_REPLICATION_USER: airflow_repl

