apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app.kubernetes.io/part-of: airflow
spec:
  selector:
    app: redis-db
  ports:
    - name: redis-db
      port: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-db
spec:
  selector:
    matchLabels:
      app: redis-db # has to match .spec.template.metadata.labels
  serviceName: redis-service
  replicas: 1 # need HA in order for DAGS to complete
  # minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: redis-db # has to match .spec.selector.matchLabels
    spec:
      # securityContext:
      #   fsGroup: 999
      # terminationGracePeriodSeconds: 10
      containers:
      - name: redis-db
        image: redis:7.0.4
        ports:
        - containerPort: 6379
          name: redis-db
        env:
        - name: MASTER
          value: "true"
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: local-storage
      resources:
        requests:
          storage: 200Mi